import exiftool
import logging
from datetime import datetime, UTC
from typing import Optional
from pathlib import Path

logger = logging.getLogger(__name__)

class MetadataRestorer:
    
    def __init__(self, file_path: Path, metadata: dict):
        """
        Initialize class variables

		Parameters
		----------
		file_path : Path
			Path to a file the metadata should be put into
		metadata : dict
			Metadata for the file itself, passed already as a dict
		"""
  
        self.file_path = file_path
        self.metadata = metadata
        
        self.photo_formats = [
            "jpg",
            "jpeg",
            "png",
            "gif",
            "webp",
            "heic",
            "heif",
            "bmp",
            "tiff",
            "tif",
            "raw",
            "arw",   # Sony
            "cr2",   # Canon
            "cr3",   # Canon (newer)
            "dng",   # Adobe / Google Pixel
            "nef",   # Nikon
            "nrw",   # Nikon (compact)
            "orf",   # Olympus
            "raf",   # Fujifilm
            "rw2",   # Panasonic
            "srw",   # Samsung
            "x3f",   # Sigma
            "pef",   # Pentax
        ]
        
        self.video_formats = [
            "mp4",
            "m4v",
            "mov",
            "avi",
            "wmv",
            "flv",
            "webm",
            "mkv",
            "3gp",
            "3g2",
            "m2ts",
            "mts",
            "mpg",
            "mpeg",
            "ogv",
        ]
       
    @staticmethod 
    def _generate_geo_metadata(
		geo_data: Optional[dict] = None,
		geo_data_exif: Optional[dict] = None
	) -> Optional[dict]:
        """
        Function to generate GPS metadata for the file

		Parameters
		----------
		geo_data : Optional[dict], optional
			Geo data generated by Google during the creation of the file, by default None
		geo_data_exif : Optional[dict], optional
			Actual geo data of the file during the creation, by default None

		Returns
		-------
		Optional[dict]
			Geo metadata or None
		"""
  
        if not geo_data and not geo_data_exif:
            return None
        
        metadata = {}
        
        obj = geo_data if geo_data else geo_data_exif
        
        lat = obj.get('latitude', 0.0)
        lon = obj.get('longitude', 0.0)
        
        if lat == 0.0 and lon == 0.0:
            return None
        
        metadata.update({
			"GPSLatitude": lat,
			"GPSLongitude": lon,
			"GPSAltitude": obj.get('altitude', 0.0),
            "GPSLatitudeRef": "N" if lat >= 0 else "S",
            "GPSLongitudeRef": "E" if lon >= 0 else "W",
		})
        
        return metadata
    
    @staticmethod
    def _format_date(timestamp: int) -> str:
        """
        Function to format a timestamp to a readable format

		Parameters
		----------
		timestamp : int
			Timestamp of the creation time of the file

		Returns
		-------
		str
			Formatted date
		"""
  
        return datetime.fromtimestamp(timestamp=timestamp, tz=UTC).strftime("%Y:%m:%d %H:%M:%S")
    
    def _extract_common_fields(self) -> dict:
        """
        Function to extract common fields from the metadata JSON file

		Returns
		-------
		dict
			Common fields as a dict
		"""
  
        return {
            "photo_taken_time": self.metadata.get("photoTakenTime", {}).get("timestamp"),
            "modification_time": self.metadata.get("modificationTime", {}).get("timestamp"),
            "description": self.metadata.get("description") or None,
            "device_type": self.metadata.get("googlePhotosOrigin", {}).get("mobileUpload", {}).get("deviceType"),
            "starred": self.metadata.get("starred", False),
            "geo_data": self.metadata.get("geoData"),
            "geo_data_exif": self.metadata.get("geoDataExif"),
        }
        
    def _generate_photo_metadata(self, fields: dict):
        """
        Function to generate photo metadata

		Parameters
		----------
		fields : dict
			Common fields that were extracted from _extract_common_fields() function

		Returns
		-------
		_type_
			Metadata of the photo
		"""
  
        metadata = {}

        if fields["photo_taken_time"]:
            metadata["AllDates"] = self._format_date(int(fields["photo_taken_time"]))

        if fields["modification_time"]:
            metadata["ModifyDate"] = self._format_date(int(fields["modification_time"]))

        if fields["description"]:
            metadata["ImageDescription"] = fields["description"]

        if fields["device_type"]:
            metadata["Make"] = fields["device_type"]

        if fields["starred"]:
            metadata["Rating"] = 5

        geo = self._generate_geo_metadata(fields["geo_data"], fields["geo_data_exif"])
        if geo:
            metadata.update(geo)

        return metadata
    
    def _generate_video_metadata(self, fields: dict):
        """
        Function to generate video metadata

		Parameters
		----------
		fields : dict
			Common fields that were extracted from _extract_common_fields() function
		Returns
		-------
		_type_
			Metadata of the video
		"""
  
        metadata = {}

        if fields["photo_taken_time"]:
            date_str = self._format_date(int(fields["photo_taken_time"]))
            metadata["QuickTime:CreateDate"] = date_str 
            metadata["QuickTime:TrackCreateDate"] = date_str
            metadata["QuickTime:MediaCreateDate"] = date_str
            
            metadata["QuickTime:ModifyDate"] = date_str
            metadata["QuickTime:TrackModifyDate"] = date_str
            metadata["QuickTime:MediaModifyDate"] = date_str
            
        if fields["modification_time"]:
            mod_str = self._format_date(int(fields["modification_time"]))
            metadata["QuickTime:ModifyDate"] = mod_str
            metadata["QuickTime:TrackModifyDate"] = mod_str
            metadata["QuickTime:MediaModifyDate"] = mod_str

        if fields["description"]:
            metadata["QuickTime:Description"] = fields["description"]
            
        if fields["device_type"]:
            metadata["QuickTime:Make"] = fields["device_type"]

        geo = self._generate_geo_metadata(fields["geo_data"], fields["geo_data_exif"])
        if geo:
            metadata.update(geo)

        return metadata
        
    def _generate_metadata(self) -> Optional[dict]:
        """
        Function that orchestrates generation of the metadata depending on the file's extension

		Returns
		-------
		Optional[dict]
			Metadata if the extension exists in either of the formats or None
		"""
  
        extension = self.file_path.suffix[1:].lower()
        common_fields = self._extract_common_fields()
        
        if extension in self.photo_formats:
            metadata = self._generate_photo_metadata(fields=common_fields)
        elif extension in self.video_formats:
            metadata = self._generate_video_metadata(fields=common_fields)
        else:
            logger.warning(f"Unsupported format: {extension} for file {self.file_path}")
            return None
            
        return metadata
    
    def restore_metadata(self) -> bool:
        """
        Function to restore metadata

		Returns
		-------
		bool
			True if metadata was restored successfully, False otherwise
		""" 
        with exiftool.ExifToolHelper() as et:
            generate_metadata = self._generate_metadata()
            if not generate_metadata:
                return False
            
            try:
                et.set_tags(
					files=self.file_path,
					tags=generate_metadata,
					params=["-P", "-overwrite_original", "-n", "-charset", "UTF8"]
				)
                logger.info(f"Successfully restored metadata for: {self.file_path}")
                return True
            except exiftool.exceptions.ExifToolExecuteError as e:
                if "minor" in et.last_stderr.lower():
                    logger.warning(f"Minor error in file {self.file_path}, retrying with -ignoreMinorErrors")
                    try:
                        et.set_tags(
							files=self.file_path,
							tags=generate_metadata,
							params=["-P", "-overwrite_original", "-n", "-charset", "UTF8", "-ignoreMinorErrors"]
						)
                        logger.info(f"Successfully restored metadata for: {self.file_path}")
                        return True
                    except exiftool.exceptions.ExifToolExecuteError:
                        logger.exception(f"Failed even with -ignoreMinorErrors for {self.file_path}")
                        return False
                logger.error(f"ExifTool stderr: {et.last_stderr}")
                logger.error(f"ExifTool stdout: {et.last_stdout}")
                logger.exception(f"Something went wrong during metadata insertion in file {self.file_path}")
                return False
